name: Publish
on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get release tag on push to main
        id: releasetag
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        run: echo '::set-output name=releasetag::type=sha,prefix=release-'
      - uses: crazy-max/ghaction-docker-meta@v2
        name: Docker meta
        id: docker_meta
        with:
          images: capeprivacy/capejail
          tags: |
            type=sha
            ${{ steps.releasetag.outputs.releasetag }}
      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.CAPEBOT_SSH_KEY }}"
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        if: github.event_name != 'pull_request' && github.actor != 'dependabot[bot]'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v2
        name: Build and push docker
        if: github.actor != 'dependabot[bot]'
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          ssh: default=/tmp/ssh_agent.sock
          build-args: |
            SERVICE_VERSION=${{ github.sha }}
